usb: dwc3: convert to livetree
Update the DWC3 USB driver to support a live tree.

Signed-off-by: Vipul Kumar <vipul.kumar@xilinx.com>
Signed-off-by: Siva Durga Prasad Paladugu <siva.durga.paladugu@xilinx.com>
Tested-by: Michal Simek <michal.simek@xilinx.com>
---
Changes in v3:
- Used ofnode_valid() to check for node validity
  This fixes the below compilation failure
  for stih410-b2260_defconfig
  LD      cmd/built-in.o
drivers/usb/host/dwc3-sti-glue.c: In function ‘sti_dwc3_glue_bind’:
drivers/usb/host/dwc3-sti-glue.c:160:16: error: invalid operands to binary <= (have ‘ofnode {aka union ofnode_union}’ and ‘int’)
  if (dwc3_node <= 0) {
                ^~
make[1]: *** [drivers/usb/host/dwc3-sti-glue.o] Error 1

Changes in v2:
- compilation failures for am335x_hs_evm_uart platform during travis ci as
  v1 didn’t made corresponding changes to drivers/usb/musb-new/ti-musb.c
  as per live tree conversion.
  Now it is fixed in v2 by moving this driver to support live tree.
  Also fixed dwc3-sti-glue.c to support live tree.